spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host:
      password:
  cloud:
    consul:
      host:
      port: 80
      discovery:
        instance-id: ${spring.application.name}