spring:
  datasource:
    url: jdbc:mysql://mysql.jidudev.com:3306/jidu_odin?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&allowMultiQueries=true
    username: odin_wr
    password: sS8pG8sD3o
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 10.80.110.5
      password: hOmp0gk9vOZa

mybatis:
  mapper-locations: classpath:mapper/**/*.xml