spring:
  datasource:
    url: ${config.mysql.url}
    username: ${config.mysql.username}
    password: ${config.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${config.redis.host}
      password: ${config.redis.password}