sa-token:
  # token名称 (同时也是cookie名称)
  token-name: authorization

spring:
  data:
    redis:
      host: ${config.redis.address}
      password: ${config.redis.password}
  cloud:
    gateway:
      routes:
      - id: banzh-web
        uri: lb://banzh-web
        predicates:
        - Path=/web/**
        filters:
          - StripPrefix=1
