spring:
  data:
    redis:
      host: ${config.redis.address}
      password: ${config.redis.password}
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: banzh-web
        uri: lb://banzh-web
        predicates:
        - Path=/web/**
        filters:
          - StripPrefix=1
