sa-token:
  # token名称 (同时也是cookie名称)
  token-name: authorization

spring:
  data:
    redis:
      host: ${config.redis.host}
      password: ${config.redis.password}
  cloud:
    gateway:
      routes:
      - id: poison-web
        uri: lb://poison-web
        predicates:
        - Path=/web/**
        filters:
          - StripPrefix=1
      - id: poison-chat
        uri: lb://poison-chat-netty-service
        predicates:
        - Path=/ws/**
        filters:
          - StripPrefix=1